<?php

/**
 * @file
 *
 * Just a bunch of debugging junk to make my life easier.
 */

/**
 * Debug Wrapper to the watch dog function, for printing variables to the log
 */
function wd() {
  $args = func_get_args();
  $args = (count($args) <= 1) ? array_shift($args) : $args;
  $message = print_r($args, TRUE);
  watchdog('debug', $message, NULL, WATCHDOG_DEBUG);
}

/**
 * Logs function call info
 */
function wd_func() {
  $trace = debug_backtrace();
  $caller = $trace[1];
  $vars = array(
    '!func' => $caller['function'],
    '!line' => $caller['line'],
    '!file' => substr($caller['file'], strlen(getcwd()) + 1), // Remove site root and leading '/'
  );
  watchdog('debug', "!func\ncalled at line !line of !file", $vars, WATCHDOG_DEBUG);
}

